server:
   port: 8600

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/
           
spring:
  application:
    name: service-feign
    
    
##开启断路器
feign:
  hystrix:
    enabled: true