server:
   port: 8800

eureka:
   serverP: 
       enable-self-preservation: false;
   instance:
       hostname: localhost
   client:
       registerWithEureka: false
       fetchRegistry: false
       serviceUrl:
           defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
           
spring:
  application:
    name: eurka-server